### ISSUE TITLE
Is boto3 needed

### ISSUE THREAD

**Issue by mims92** [tazatwell/ssm-securestring-cfn-macro#11]
The `requirements.txt` includes `boto3` but I don't think it is needed as it is already included in the Lambda runtime.

Unless you need a specific version, it can be removed from the `requirements.txt` file.

It will also reduce the overall package size.

**Comment by tazatwell** [comment]
You're right , `boto3` and its dependencies are already in the lambda runtime, its not needed. Removed, tested, and merged in https://github.com/tazatwell/ssm-securestring-cfn-macro/pull/14.

Thank you for noticing!
