### ISSUE TITLE
Please add license information to your repository

### ISSUE THREAD

**Issue by wombelix** [tazatwell/ssm-securestring-cfn-macro#12]
Hey @tazatwell,
I really like your cfn macro to solve the problem of missing `SecureString` support in CloudFormation, thanks for your work! 
Unfortunately there isn't a license attached to the repository or mentioned in your README or the source code. 
This makes it impossible for others to use your macro. It's not enough to make it public on GitHub. 
Personally I would suggest `MIT` for such a project. To manage the license compliance I prefer https://reuse.software.
If you are unsure, pages like https://choosealicense.com/ can help you to select a open source license.
Dom

**Comment by tazatwell** [comment]
Hi , thank you for the helpful links, this is my first licensed repository.

Sorry for the delay, license is added.
